apiVersion: v1
kind: Secret
metadata:
    name: approved-reg-pull-cred
data:
    .dockerconfigjson: ENC[AES256_GCM,data:USo1WUnZw9JBVC71Z+h7nGugMjJmfeKlkHXKG8v5Jy8e8NEg1FgRL1eJvSfdD4JfYVxVnj69nQAzx92DPwOMm5+alL+AqNH9OT3MlBto5n5YMT8L1ZUNF2fK1zSkAb5epiRtbbtEZkMupd0VIbrOpAeTwNWDODAvNHKu2k42hGOv3ADgUr+SBD3q4y7aIGFZwPfXHRANyZnb0uGRfDeVlepCLMIVIwQfdkmdRRL/3UB9oc4qV2zil5O53trw+cTA9s44hg==,iv:QT6sn+NQcfL4xFo65D3xvpEiyWSaUMumYiFihzaqfP0=,tag:28Gt8NPqzsITksg8Gs17Mw==,type:str]
type: kubernetes.io/dockerconfigjson
sops:
    kms:
        - arn: arn:aws-us-gov:kms:us-gov-east-1:625057868947:alias/tst-il2-project-blue-sops
          created_at: "2022-01-25T21:14:02Z"
          enc: AQICAHhITpQkQvIaPOQZHOvVqFiHcqMRjho5t9l9HRJCn5qGhgFr4WyoZ3nXI+tTQCpxVgaeAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM9iiHRw4VxByHtUWIAgEQgDuENi0Wd/J9JKONJywsniCqiuhbvi3A0G1jaDzZbrIxirc2htvz0KgbV7qRY1P2xtE3YKWJ5I4DiS2vAg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-25T21:14:02Z"
    mac: ENC[AES256_GCM,data:dRjFWgDhBntYv9b7PxULObad5RPmo+/7r5G/QViKU4ufNKfBFFxvNygx4FpWAY4JIacC1+uEqqEfihuQtf4nO2Z1BJla3DR5Yc3HIN056Jnxwu7rM+gIWEJRKTP4AniBJ33aaUkrr0QEIyMRDy9cB1ghNZu7mz4+7VOCs/eo6AY=,iv:8B2nmWqOOJY9+a0MV0uq1GFgFHT0IIbdsLIbAss4N6A=,tag:jkx9Oc+JxxwKWyf5LoCY5Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
