apiVersion: v1
kind: Secret
metadata:
    name: git-data-creds
    namespace: beast-core
data:
    USERNAME: ENC[AES256_GCM,data:teFYwYDc5RoeJ8ZO,iv:qXvRkniCuLURiwYLUoOLEjy/+BJNU4jvchlNJezmxlM=,tag:tstLbd3VNC5TOpGBL6YpZg==,type:str]
    TOKEN: ENC[AES256_GCM,data:ufTGcnYdaM5TGTE27BKF6H1Vzq9NWufTGnMwIw==,iv:xswiazbLsiBKZ+32pMRTdMcbWFn+w7rqdECFh7v570o=,tag:YKOCGYML92xnEMbjQ2aOrg==,type:str]
sops:
    kms:
        - arn: arn:aws-us-gov:kms:us-gov-east-1:625057868947:alias/tst-il2-project-blue-sops
          created_at: "2022-01-31T14:58:57Z"
          enc: AQICAHhITpQkQvIaPOQZHOvVqFiHcqMRjho5t9l9HRJCn5qGhgGcKapiIomM7QHuwlg7HviSAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM5oETAZIoKnfPiyJcAgEQgDuezYz1MdCojYu/uB1j4GUOtoZIv/GuHjoeK3YmnlqftOSXIW4LP659RGEsshh4wpDB9sKauiYKPeTKag==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-31T14:58:57Z"
    mac: ENC[AES256_GCM,data:vQzzUmZnuX4cXpo3eAwEjVkaPrpD8jOQHd/l/zp5ZaT3Efe5C5SJbcaIzQNxxVt5Bzr264JWOBE5Xzo8Cn6XX22c/lMUDoJfB4LRCrgVVRj3cD0W6kCyZzCwai6y/IUOYwx+++CZAa5smPEJEPhOfiUsgDyb8FIuTENSCe4Xc10=,iv:7Rz7smw+CNt4PfXDgFk02k8tA/YXU/aGxHasWjAZnqg=,tag:HDfSYv6ziDust0sRxQLZJQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
