apiVersion: v1
kind: Secret
metadata:
    name: git-data-creds
    namespace: beast-core
data:
    USERNAME: ENC[AES256_GCM,data:DnOt/wWGixinV1bZ,iv:3Xwm/sKmbAqV5xK7Motrs1PpZ9xt3x4FEJtWjfayCaQ=,tag:ocPcPpenr1w3USqtFUGizQ==,type:str]
    TOKEN: ENC[AES256_GCM,data:8rTqAOaXMGu9TEfxZ41eEzf19Rrjx5eX4KRIYA==,iv:HJIg921624nSjtBoVBbnm8pg7TL0P2Mw9m7JdDR2TIs=,tag:gW6SYG60rzlgsvhDDAKOtg==,type:str]
sops:
    kms:
        - arn: arn:aws-us-gov:kms:us-gov-east-1:664024519452:alias/stg-il4-project-blue-sops
          created_at: "2022-01-28T20:20:22Z"
          enc: AQICAHgYNkaTdMhxKckTTZvPCH9720NMpsy10eMzP8los4m3fwFuYTB7HHxo+icEQEnwEwMmAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMIJ1/DteNMLcByH4BAgEQgDtPzYkq/qAV86v8+YzK57ZrrMJYXZBrfdTD7bucdpFdvIJEaslCFDftm2FnY8AYbdABq8cPfo9SUJ7aLQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-28T20:20:23Z"
    mac: ENC[AES256_GCM,data:Yq0R0rySjBZpMO5Ly6XBkaYA/GE4uxEJYSAhroE+1QL64uKgTDTWHggEG6bDTQgANqkPF9fBMmjWhuvrypQ/8YBUBWEmf5I4XDKR577ZMU7pLQUPXpZO6MJO5cGcLse0tGEy+uUEId+8KsTE2uWZVQ/RfTPvWjLhLFU7BMpFgoA=,iv:fK2IRh3xgQpJIKT0upRp1WbgJzWfE3Va4mp7k07wtQM=,tag:vJqc7lNuRersuVIZAjUfTQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
