apiVersion: v1
kind: Secret
metadata:
    name: approved-reg-pull-cred
data:
    .dockerconfigjson: ENC[AES256_GCM,data:QIe607rCHfuaA5PLgoSEucATxDMfGOkIkbUhTT1HPfLEZMjunM6LhH8VnBuUPje5N9NUUJtChA6cE2jbahms/T/ZY+Vi8JfGNiLSHDzA9v74r+NUvyF+D02nMVSxZb0lP3wUlpewV9lEmEWTnmOwAfa9I5NVvHVQ2iIWd2oSm2FIxud2/TaEm7EavBJl/U3vBOtuINx6XBWewQr0sUsb6Siuju5iV/SJ9BAiWuyJ0KUh8P8Cskqd6t48cEnB1hXI3yxtOw==,iv:LbggkROH0X4AcYvdGk5uKiSgvLEUR0bkB9aU+okYQWg=,tag:jw5WCnTOlWoOoc6Roy6xyg==,type:str]
type: kubernetes.io/dockerconfigjson
sops:
    kms:
        - arn: arn:aws-us-gov:kms:us-gov-east-1:417116289550:alias/dev-il2-project-blue-sops
          created_at: "2021-12-15T22:40:30Z"
          enc: AQICAHhR6nWC/QZXSe3EE0Mr0x6pxqdAoGDffjDfy9LF3o+9PwHuT9xav+rz20icNDPmFHHwAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMhj5hOzzRMxaZo8DOAgEQgDvDVKxBa+x30ODnQKoczcIeNZldzCfm2fqWzohaLAWEhykQxhM5BOX/+bF3D2GzoLr8wlQH3J2r0bu5yQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-15T22:40:30Z"
    mac: ENC[AES256_GCM,data:QcsMz5pxQQnSDclCdWQe1azM3siHEQjFFttozp/W1T0OJc50ZrCasnYp4q1+a8kZ7xVOOoxuMSibuYnlc+TW2U/7dM20NDdk+3FHfM88BN5gPH3mntu58y33ImEuUaq+l0Y6olZjT5tWY5fU3ONE3dQP0wW0k1rP6RnFXj/MyLI=,iv:qU/rCHkUE30HF8jaSMfBxndLH9NFGYoqyEIXpVbxp+Q=,tag:xbB4xmfF6WOCL6W4UC8REg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
