apiVersion: v1
kind: Secret
metadata:
    name: git-data-creds
    namespace: beast-core
data:
    USERNAME: ENC[AES256_GCM,data:kgSFf/SDf+YsrIHh,iv:Rj8TDEnVkmOmsJm6+Obgn02dMqdNJq49ylbyhSsGx2U=,tag:pVgV+DFzEjfdcNZpnjnbNQ==,type:str]
    TOKEN: ENC[AES256_GCM,data:5GSSVshoEQzFAcFkQIrrTBVukm2pJlHHuN8LiQ==,iv:Xh5MGRfY5abGSpYbJNsa4YpujpUHaJlkGyUekA64C9o=,tag:ocjjUar8X0bz0559al7p8Q==,type:str]
sops:
    kms:
        - arn: arn:aws-us-gov:kms:us-gov-east-1:417116289550:alias/dev-il2-project-blue-sops
          created_at: "2021-12-15T15:05:40Z"
          enc: AQICAHjqntOligptQ58bSl4ciSd0ViPjsuvqOZcW8crkCZQpvwEKcP+PKj/rzsW0woqA8yShAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMcpvErkSoXH6dw6i/AgEQgDtCmGbe9NbYfkZDHiTsUSSPc467P8R2fdUTMnYdNXNLc58f1D9Y+SpJI7nZUBjhWjkV07a97ElBYdbaLg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-15T15:05:41Z"
    mac: ENC[AES256_GCM,data:tNP0x5/6jj5uOPWOTga4y5lV8dhXSQbIz1P4MmrkBhK5v+30O9QEJfCw7f/tKIx2neue5B7Jc2bP2VM7XcEb6hqM9NaXJUniSq3YIWxfEEb3LdbUyGPOrz13VfF1Q1D6xROIFosO7DG+2RA+JMn8/LE2uP5iqoFL5ZtzYeb9qkI=,iv:MLG1bmJ6ZIDWwLPZXydFNKSHwyWoS1DJOgzfq2gOyIE=,tag:5QLKJmQLkapQPAfSl2XeOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
