apiVersion: v1
kind: Secret
metadata:
    name: git-data-creds
    namespace: beast-core
data:
    USERNAME: ENC[AES256_GCM,data:YgfTPUr+nfu2v49s,iv:rK2s0TZSBlfGzfLuK9dB9J22Aupkn1Q59qeLLLITUZA=,tag:UidCuNlKm3TFRdB/2kM3xA==,type:str]
    TOKEN: ENC[AES256_GCM,data:XTYIwlGmV0sDVSh2POnQr9XXLp4urvkcRM8l5w==,iv:wuVfVZaGBip9ELzR8WM41jdG2zkIGZO+tsgR+ZsOnuI=,tag:TyrpboQKBy1SUjNlIDGohg==,type:str]
sops:
    kms:
        - arn: arn:aws-us-gov:kms:us-gov-east-1:417116289550:alias/dev-il2-project-blue-sops
          created_at: "2021-12-06T19:08:29Z"
          enc: AQICAHhRo4u61Id3SGnSoSJLuzkjGZ1vQT8BUmYwfHSnM0RvYAFPaov4Ap36Vxn23xo8q39uAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMb6b65AUwGbojb5fSAgEQgDslf/I08qG+I5130mbGfv8XSTzECPqwh172OhjNYNPgi5AjcBMzUGG7M+WNYXneF085IAO2gzjo7LVe9Q==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-06T19:08:30Z"
    mac: ENC[AES256_GCM,data:DNO6UI1la5erhOTz/v5xmdSWwaZ0Gd40nQ2GkMY9wlpvjMEtGYZOhowTrZrAVtZ+RaI33+WMyQt5AP2zvAx5yrjls7qb8msQWwghudRwKEy4xpWxhltsVJ2ciXQq2QxP4A6KEAOhpvrNqvyi3lpxmHXY8VN4W2ilSQFXhSipfCY=,iv:6g8l9s/MYciGLDcAoOWjN0LOPYQMIGssU/8jN0cJvUg=,tag:eY6GuJ7HJtwO35KBXV1VPQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
