apiVersion: v1
kind: Secret
metadata:
    name: git-data-creds
    namespace: beast-core
data:
    USERNAME: ENC[AES256_GCM,data:aEV8PHzO9GZCGSYR,iv:vwIBRiJfAJowR9EmjxmHFIsXq/Jsv6ByclF3qLYZF+c=,tag:uWVu32pK5+M6ffv6CfDyqA==,type:str]
    TOKEN: ENC[AES256_GCM,data:FPPVRj0nVL0l3TY3hpf8x97TqzzkIL2SNJX8pA==,iv:2FCjFUS3prueyiaF1BpT2w+jkx0FTF6hTTOCTv4mfMY=,tag:13Gt28PkKainWPlO9nGsvQ==,type:str]
sops:
    kms:
        - arn: arn:aws-us-gov:kms:us-gov-east-1:664024519452:alias/stg-il4-second-front-sops
          created_at: "2022-02-28T16:43:32Z"
          enc: AQICAHgWgP5GQhrDd0ZovE/lrl3gd0chEM+SdJpEzPXiW0x/hwFnYCDDtPRdSDwhzgvvjyk1AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM43sfRsuTzjxDcZ/EAgEQgDuvMwbpDVGHCKHuW0U5zxxda96GPFrbLC7PXkbvgMwLy+zWvxLy97bbLM74SnTmiYB4bJMBV8aCchhsDA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-28T16:43:33Z"
    mac: ENC[AES256_GCM,data:m7cuMhQN8r8DihSWbbbb/tD7WyatjY/VUO/y4Ku0vi0JP4G508o89HXm+45pUSmZRtMe9fBiJAIleCcCZZvMkNA1HJRnuLzWZpNLtf96FYARK+OR3QiXWjLBpBY4N9TZJtbxwhIZkHp9Fcmv9x63EUi4gp4dR22mSn5rUoBCI3g=,iv:V4xz/IFYy80YalE10dth2eycA+w0JhPeanonolzNlzk=,tag:GHVezBsBDTQTiRYZppWL4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
