bases:
  - ../../base/

images:
- name: beast-code-core
  newName: registry1.dso.mil/ironbank/beast-code/beast-core/base-image
  newTag: "3.4.1"
- name: data-loader
  newName: registry.il5.dso.mil/platform-one/devops/pipeline-templates/beast-code-init/ironbank-bitnami-git-lfs
  newTag: "2.31.1"

patchesStrategicMerge:
- patches/deployment-patch.yaml
