resources:
- ../../../base
- flux-kustomization.yaml

      # updated for CNAP
      # updated for CNAP
      # updated for CNAP
      # updated for CNAP
      # updated for CNAP
      # updated for CNAP
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: beast-core
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: nexus-registry
            - name: private-registry
            - name: gw-reg-pull-cred
  target:
    kind: Deployment
- patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: git-repo
    data:
      GIT_REPO: code.il2.gamewarden.io/agencies/project-blue/beast-core-application/beast-core-data-mirror.git
  target:
    kind: ConfigMap
- patch: |-
    apiVersion: networking.istio.io/v1beta1
    kind: VirtualService
    metadata:
      name: beast-core-vs
    spec:
      gateways:
      # updated for CNAP
      - istio-system/private
      hosts:
      - beast-core.stg.il4.project-blue.gamewarden.io
  target:
    kind: VirtualService
- patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: cluster-prefix
    data:
      CLUSTER_PREFIX: il4-stg
  target:
    kind: ConfigMap

  # newName: registry1.dso.mil/ironbank/bitnami/git
images:
- name: beast-core
  newName: registry-approved.il2.gamewarden.io/agencies/project-blue/beast-core-app
  newTag: 3.10.0
- name: data-loader
  newName: registry1.dso.mil/ironbank/opensource/git-lfs/git-lfs
  newTag: 2.35.1-3.1.2
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
